### ISSUE TITLE
RenewalService: Exception occured renewing certificates: 'Value cannot be null. Parameter name: source.'

### ISSUE THREAD

**Issue by srudin** [ffMathy/FluffySpoon.AspNet.LetsEncrypt#18] opened 2019-11-21 14:08 UTC
I integrated the nuget package of this component some weeks ago into our prject and deployed it to our preview environment. Everything was working fine, certificates were acquired and https was working.
Yesterday I deployed a new version of our project that included the package update from 122 to 125. I am now no longer able to connect to the website. I can see the following error:

`FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService
Exception occured renewing certificates: 'Value cannot be null.
Parameter name: source.'

System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable'1 source, Func'2 predicate)
   at FluffySpoon.AspNet.LetsEncrypt.Persistence.PersistenceService.<>c__DisplayClass13_0.<PersistChallengesAsync>b__0(IChallengePersistenceStrategy x)
   at System.Linq.Enumerable.SelectArrayIterator'2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable'1 tasks)
   at FluffySpoon.AspNet.LetsEncrypt.Persistence.PersistenceService.PersistChallengesAsync(IEnumerable'1 challenges, IEnumerable'1 strategies)
   at FluffySpoon.AspNet.LetsEncrypt.Persistence.PersistenceService.PersistChallengesAsync(ChallengeDto[] challenges)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.AcquireNewCertificateForDomains(String[] domains)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync()`

I am a bit confused as I think I didn't change anything relevant - could there be a bug in the new package?
I am making very basic use of the component following almost exactly the tutorial (without the optional stuff). Any quick ideas? Any known issues?

**Comment by srudin** [comment] 2019-11-22 05:14
The package is definitely broken!
I tried versions 125 and 126 and always got the above error. The client sees ERR_CONNECTION_CLOSED in the browser.
Then I rolled back to 122 (this was the only change) and immediately it started working again. Please have a look and fix this, thx!

**Comment by killswtch** [comment] 2019-11-22 09:22
This issue was addressed by PR #17. I'm not sure what version that corresponds to though.

**Comment by ffMathy** [comment] 2019-11-22 09:23
Ah, so updating to version 126 will fix the issue.

Thanks!

**Comment by srudin** [comment] 2019-11-25 05:24
Ok, I'll try, thx.

**Comment by srudin** [comment] 2019-11-27 12:19
126 is NOT fixing the issue.

After upgrading I get:

FluffySpoon.AspNet.LetsEncrypt.ILetsEncryptRenewalService
Exception occured renewing certificates: 'Object reference not set to an instance of an object..'

System.NullReferenceException: Object reference not set to an instance of an object.
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.<>c.<ValidateOrderAsync>b__28_5(Challenge x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.ValidateOrderAsync(String[] domains, IOrderContext order)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.AcquireNewCertificateForDomains(String[] domains)
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceAsync()
   at FluffySpoon.AspNet.LetsEncrypt.LetsEncryptRenewalService.RunOnceWithErrorHandlingAsync()

Seems the details are a bit different but the result is the same: the package is NOT working anymore.

Please also see https://github.com/ffMathy/FluffySpoon.AspNet.LetsEncrypt/issues/19 which seems to be related.

**Comment by ffMathy** [comment] 2019-11-27 12:26
@killswtch any other ideas? It must have been added in the PRs.

I don't have much time to look into it these days.

@srudin can you try fetching the sources down and diagnose it that way? Perhaps even make a PR?

**Comment by killswtch** [comment] 2019-11-27 12:40
The only thing that appears to match the stack trace above is the Linq expression in lines 270-273 of LetsEncryptRenewalService.cs, which has had few changes. Much of the work is being done by Certes. Only thing I can suggest is to put a null check in, ensuring there are no nulls in the Challenge[] array that is iterated in the status check.

**Comment by ffMathy** [comment] 2019-11-27 12:43
I have deployed a version 1.0.127 which should have source link enabled. It doesn't fix the problem, but should make it possible to browse the nuget source code and set breakpoints in it via Visual Studio directly, making it easier to figure out the root cause.

@killswtch thanks for your continued efforts.

**Comment by ffMathy** [comment] 2019-12-02 08:25
Did 1.128.0 improve this issue?

**Closed** 2019-12-10 19:40 UTC
